kill bar pid after exiting dwm

diff --git a/home/bin/start_dwm b/home/bin/start_dwm
--- a/home/bin/start_dwm
+++ b/home/bin/start_dwm
@@ -3,6 +3,28 @@
 # and will in turn execute $session_startfile
 
 # ==============================
+# env vars import has to be the first thing:
+if [[ "$__ENV_VARS_LOADED_MARKER_VAR" != "loaded" ]]; then
+    _global_env_var_loc='/etc/.bash_env_vars'
+
+    if [[ -r "$_global_env_var_loc" ]]; then
+        source "$_global_env_var_loc"
+    else
+        echo -e "\nError: env vars file \"$_global_env_var_loc\" not found! Abort."
+        exit 1
+    fi
+fi
+####
+# import common:
+if ! type __COMMONS_LOADED_MARKER > /dev/null 2>&1; then
+    if [[ -r "$_SCRIPTS_COMMONS" ]]; then
+        source "$_SCRIPTS_COMMONS"
+    else
+        echo -e "\nError: common file \"$_SCRIPTS_COMMONS\" not found! Abort."
+        exit 1
+    fi
+fi
+# ==============================
 
 # skip, if dwm is already running:
 if [[ "$(ps -e | grep "\bdwm\b")" ]]; then
